version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
      - image: mysql:5.7.31
        command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: company
        MYSQL_PASSWORD: password
    
    steps:
    - checkout 
    - run:
          name: Install things we need
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev
            sudo apt-get install -y zlib1g-dev libicu-dev g++
            sudo apt-get install mysql-client
            sudo apt-get -y install mysql-server
    - run:
          name: Start database server
          command: |
            sudo service mysql start
            sleep 2
            ps aux | grep mysql
    - run:
          name: npm
          command: |
            npm install mysql --save
            npm install express --save
            npm install
    - run:
          name: Create non-admin user
          command: |
            sudo mysql -u root -e "CREATE USER user IDENTIFIED BY 'password';"
            sudo mysql -u root -e "FLUSH PRIVILEGES";
            sudo mysql -u root -e "SELECT user,host,account_locked,password_expired FROM mysql.user;"
            sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';"
            sudo mysql -u root -e "FLUSH PRIVILEGES";
            mysql --version
            node --version
            
    - run:
          name: database connection
          command: |
            node server.js       
workflows:
  build_and_test:
    jobs:
      - build 
