version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
      - image: mysql:8.0.12
        command: --default-authentication-plugin=mysql_native_password
    environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: test #this is optional if require than set it
          MYSQL_PASSWORD: password #this is optional if require than set it
    steps:
    - checkout 
    - run:
          name: Install things we need
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev
            sudo apt-get install -y zlib1g-dev libicu-dev g++
            sudo apt-get install mysql-client
            sudo apt-get -y install mysql-server
    - run:
          name: Start database server
          command: |
            sudo service mysql start
            sleep 2
            ps aux | grep mysql
    - run:
          name: npm
          command: |
            npm install mysql --save
            npm install
    - run:
          name: Create non-admin user
          command: |
            sudo mysql -u root -e "CREATE user myuser IDENTIFIED BY 'password';" 
            mysql --version
            node --version
            node server.js
workflows:
  build_and_test:
    jobs:
      - build 
