version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: company
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        
    steps:
      - checkout
      - run:
          name: Install MySQL CLi
          command: |
            
            sudo apt-get install default-mysql-client
            mysql -uroot -p$MYSQL_ROOT_PASSWORD --socket=/var/run/mysqld/mysqld.sock -e "grant all privileges on *.* to '$MYSQL_USER'@'%' identified by '$MYSQL_PASSWORD';"
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
