version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install mysql-server
      - run: mysql_secure_installation
      - run:
          name: Mysql database
          command: mysql -h 127.0.0.1 -u root -e "create database mate;"
     
workflows:
  build_and_test:
    jobs:
      - build 
