version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-node-browsers # The primary container where steps are run
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: company
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLi
          command: |
            mysql -uroot -ppassword --socket=/var/run/mysqld/mysqld.sock -e "grant all privileges on *.* to '$user'@'%' identified by 'password';"
            sudo apt-get install default-mysql-client
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
