version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
        environment:
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0.15
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Mysql database
          command: mysql -h 127.0.0.1 -u root -e "create database mate;"
     
workflows:
  build_and_test:
    jobs:
      - build 
