version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
      - image: circleci/mysql:8.0.4
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: company
            MYSQL_USER: test
            MYSQL_PASSWORD: password
      
    steps:
      - checkout
      - run: npm install
      - run: node --version
    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get install default-mysql-client
            mysql -V
            mysqld --version
      
workflows:
  build_and_test:
    jobs:
      - build
