version: 2.1
jobs:
  build:
    docker:
    - image: circleci/php:7.1-node-browsers
    - image: tkuchiki/delayed-mysql
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: circle_test
    steps:
      - checkout
      - run: sudo apt-get install mysql-client --allow-unauthenticated
      - run: mysql -u root -e "create database production_flow" --protocol=tcp
     
workflows:
  build_and_test:
    jobs:
      - build 
