version: 2.1
jobs:
  build:
    docker:
     
      - image: cimg/node:14.0.0
     
      
    steps:
      - checkout
      - run: npm install
      - run: sudo apt-get install mysql-server
      - run: mysql --version
      - run: node --version
workflows:
  build_and_test:
    jobs:
      - build
