version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run: mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "CREATE USER 'user'@'%' IDENTIFIED WITH mysql_native_password BY 'password';"
      - run: npm install
      - run: node --version
      - run: sudo apt-get install default-mysql-client 
workflows:
  build_and_test:
    jobs:
      - build 
