version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
      - image: circleci/mysql:5.7
        
    steps:
      - checkout
      - run: npm install
      - run: apt-get update && apt-get install -y mysql-client 
      - run: node --version
     
workflows:
  build_and_test:
    jobs:
      - build 
